const DataBike = [
  {
    id: 1,
    list: "Cao Cấp",
    name: "Thenon s",
    urlImage: "images/Header/NavMenu/evo_200_lite.png",
    desc: "2023 | eBike",
    title: "Từ 69.900.000 VNĐ",
  },
  {
    id: 2,
    list: "Cao Cấp",
    name: "Thenon ",
    urlImage: "images/Header/NavMenu/evo_200.png",
    desc: "2026 | eBike",
    title: "Từ 63.900.000 VNĐ",
  },
  {
    id: 3,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/Feliz.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 4,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/FelizS.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 5,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/klaraa2.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 6,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/KlaraS.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 7,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/klaraa2.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 8,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 9,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/ludo.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 10,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 11,
    list: "Phổ Thông",
    name: "zss",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },

  {
    id: 12,
    list: "Trung Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 13,
    list: "Trung Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/Feliz.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 13,
    list: "Trung Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/Feliz.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 13,
    list: "Trung Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/Feliz.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 13,
    list: "Trung Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/Feliz.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
];
export default DataBike;
