const imageFiles = [
  "evo_200_lite.png",
  "evo_200.png",
  "Feliz.png",
  "FelizS.png",
  "image96.png",
  "image192.png",
  "image137.png",
  "image120.png",
  "image193.png",
  "image.png",
  "impes.png",
  "klaraa2.png",
  "KlaraS.png",
  "ludo.png",
  "tempest.png",
  "theon-S.png",
  "vento-S.png",
];

const DataBike = [
  {
    id: 1,
    list: "Cao Cấp",
    name: "Thenon s",
    urlImage: "images/Header/NavMenu/evo_200_lite.png",
    desc: "2023 | eBike",
    title: "Từ 69.900.000 VNĐ",
  },
  {
    id: 2,
    list: "Cao Cấp",
    name: "Thenon ",
    urlImage: "images/Header/NavMenu/theon.png",
    desc: "2026 | eBike",
    title: "Từ 63.900.000 VNĐ",
  },
  {
    id: 3,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 4,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 5,
    list: "Cao Cấp",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 6,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 7,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 8,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 9,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 10,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 11,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 12,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
  {
    id: 13,
    list: "Phổ Thông",
    name: "Vento s",
    urlImage: "images/Header/NavMenu/vento-S.png",
    desc: "2024 | eBike",
    title: "Từ 56.000.000 VNĐ",
  },
];
export default DataBike;
